language: c++
compiler: g++
before_script:
- git clone https://github.com/LucianoPC/test_node.git
- sudo apt-get install libcppunit-dev g++-4.9
script:
- make run_tests
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
